### ISSUE TITLE
add to ndx catalog

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/ndx-extract#2]
https://nwb-extensions.github.io/

Instructions: https://github.com/nwb-extensions/ndx-template/blob/main/%7B%7B%20cookiecutter.namespace%20%7D%7D/NEXTSTEPS.md

**Comment by weiglszonja** [comment]
The corresponding [PR](https://github.com/nwb-extensions/staged-extensions/pull/28) is already open, just made the updates for https://pypi.org/project/ndx-extract/0.2.0/.

**Comment by rly** [comment]
Please make a git tag for version 0.2.0

**Comment by weiglszonja** [comment]
@rly did it now: https://github.com/catalystneuro/ndx-extract/tags

**Comment by rly** [comment]
Awesome. Thank you. The extension has been added to the catalog: https://github.com/nwb-extensions/ndx-extract-record
