### ISSUE TITLE
In extensions.yaml, docstrings say "int32ean" in multiple places

### ISSUE THREAD

**Issue by rly** [catalystneuro/ndx-extract#3]
"int32ean" -> "boolean" ?
This seems like a find-and-replace accident.
```
    doc: int32ean flag indicating data preprocessing before main EXTRACT function
```

**Comment by rly** [comment]
Related: are these attributes supposed to be boolean?

**Comment by weiglszonja** [comment]
@rly I opened #4 where I'm changing these attributes to boolean. 
Reading these in `h5py` they show up as `uint8`, but similarly to that example, the attribute `preprocess` of `1` would indicate to run preprocessing, so ultimately I felt they should be written as `True`/`False` values. @bendichter explained to me the complexity of writing values as `boolean`, so I'm okay with keeping them how we read them in `h5py`. How do you feel about this?
